/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/models/R32.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function R32(props) {
  const { nodes, materials } = useGLTF('/R32.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[65,0,30]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.misc} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.orange_glass} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.red_glass} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['brake_disc.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['brake_disc1.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.interior} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.car_paint} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.logo1} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.backlight} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['nothing.']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['numberplate.001']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.wheel_metal} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['rubber.001']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['plastic.003']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.backlight_chrome} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.dark_red_glass} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.logo2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.chrome} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.clear_glass} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.logo4} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.logo3} />
      </group>
    </group>
  )
}

useGLTF.preload('/R32.gltf')
