/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/models/scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group position={[5,0,5]} {...props} dispose={null}>
      <pointLight  intensity={2} decay={2} position={[0, 24, 3]} rotation={[-Math.PI / 2, 0, 0]}  />
      <mesh geometry={nodes.Table.geometry} material={materials.TableWood} position={[0, 3.284, -0.791]} rotation={[Math.PI, 0, Math.PI]} scale={[3.287, 0.112, 1.4]} />
      <group position={[-2.358, 4.325, -0.855]} scale={[0.495, 1, 1]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['PC Outside']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['PC Inside']} />
      </group>
      <group position={[0.35, 4.73, -0.973]} scale={[1.656, 1, 0.052]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Monitor} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.MonitorScreen} />
      </group>
      <group position={[-0.4, 3.37, -0.196]} scale={[1, 0.05, 0.392]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.KeyboardKeys} />
      </group>
      <mesh geometry={nodes.Mousepad.geometry} material={materials.Mousepad}  position={[1.35, 3.32, -0.2]} scale={[0.7,0.7,0.7]}/>
      <mesh geometry={nodes.Mouse.geometry} material={materials.Mouse}  position={[1, 3.327, -0.306]} rotation={[0, 0.191, 0]} scale={0.22} />
      <group position={[0., 0.355, 2]} rotation={[Math.PI / 2, 0, -3.104]} scale={0.01}>
        <mesh geometry={nodes.SM_Prop_Chair_04_2.geometry} material={materials.ChairMaterial} />
        <mesh geometry={nodes.SM_Prop_Chair_04_2_1.geometry} material={materials.ChairMetal} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Ground} position={[0, 0.262, 0]} scale={[8.044, 0.117, 8.044]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
